<?php

namespace ContainerFdodtBX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_AuditService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'app.audit' shared autowired service.
     *
     * @return \Monolog\Logger
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'AuditTrailHandler.php';

        return $container->services['app.audit'] = new \Monolog\Logger('audit', [($container->services['PHPMaker2026\\Project2\\AuditTrailHandler'] ??= new \PHPMaker2026\Project2\AuditTrailHandler((\dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'log/audit.log')))]);
    }
}
