<?php

namespace ContainerFdodtBX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRuntimeLinkProviderService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\RuntimeLinkProvider' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\RuntimeLinkProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'psr'.\DIRECTORY_SEPARATOR.'link'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'LinkProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'psr'.\DIRECTORY_SEPARATOR.'link'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EvolvableLinkProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'RuntimeLinkProvider.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'LinkProviderFactory.php';

        return $container->services['PHPMaker2026\\Project2\\RuntimeLinkProvider'] = new \PHPMaker2026\Project2\RuntimeLinkProvider(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)), ($container->services['PHPMaker2026\\Project2\\LinkProviderFactory'] ??= new \PHPMaker2026\Project2\LinkProviderFactory()), $container->parameters['app.links']);
    }
}
