<?php

namespace ContainerFdodtBX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReflection_Enum_AllowService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'reflection.enum.allow' shared autowired service.
     *
     * @return \ReflectionEnum
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['reflection.enum.allow'] = new \ReflectionEnum('PHPMaker2026\\Project2\\Allow');
    }
}
