<?php

namespace ContainerFdodtBX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundTblControllerdeleteService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vVNT3h6.PHPMaker2026\Project2\RefundTblController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['services', 'PHPMaker2026\\Project2\\RefundTblDelete', 'getRefundTblDeleteService', true],
        ], [
            'page' => 'PHPMaker2026\\Project2\\RefundTblDelete',
        ]))->withContext('PHPMaker2026\\Project2\\RefundTblController::delete()', $container);

        if (isset($container->privates['.service_locator.vVNT3h6.PHPMaker2026\\Project2\\RefundTblController::delete()'])) {
            return $container->privates['.service_locator.vVNT3h6.PHPMaker2026\\Project2\\RefundTblController::delete()'];
        }

        return $container->privates['.service_locator.vVNT3h6.PHPMaker2026\\Project2\\RefundTblController::delete()'] = $instance;
    }
}
