<?php

namespace ContainerFdodtBX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipesCommand_LazyService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.PHPMaker2026\Project2\Command\RecipesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.PHPMaker2026\\Project2\\Command\\RecipesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:recipes', ['app:recipes:install', 'app:recipes:update', 'app:recipes|app:recipes:install|app:recipes:update'], 'Proxy for Composer Flex recipe commands (show, install, update) with Flex auto-toggle.', false, #[\Closure(name: 'PHPMaker2026\\Project2\\Command\\RecipesCommand')] fn (): \PHPMaker2026\Project2\Command\RecipesCommand => ($container->services['PHPMaker2026\\Project2\\Command\\RecipesCommand'] ?? $container->load('getRecipesCommandService')));
    }
}
