<?php

namespace ContainerFdodtBX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundTblControllereditService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3LL3WB0.PHPMaker2026\Project2\RefundTblController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['services', 'PHPMaker2026\\Project2\\RefundTblEdit', 'getRefundTblEditService', true],
        ], [
            'page' => 'PHPMaker2026\\Project2\\RefundTblEdit',
        ]))->withContext('PHPMaker2026\\Project2\\RefundTblController::edit()', $container);

        if (isset($container->privates['.service_locator.3LL3WB0.PHPMaker2026\\Project2\\RefundTblController::edit()'])) {
            return $container->privates['.service_locator.3LL3WB0.PHPMaker2026\\Project2\\RefundTblController::edit()'];
        }

        return $container->privates['.service_locator.3LL3WB0.PHPMaker2026\\Project2\\RefundTblController::edit()'] = $instance;
    }
}
