<?php

namespace ContainerFdodtBX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemTimeProviderService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\SystemTimeProvider' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\SystemTimeProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PHPMaker2026\\Project2\\SystemTimeProvider'] = new \PHPMaker2026\Project2\SystemTimeProvider();
    }
}
