<?php

namespace ContainerFdodtBX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_UserChecker_Chain_MainService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.user_checker.chain.main' shared service.
     *
     * @return \Symfony\Component\Security\Core\User\ChainUserChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'UserCheckerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'ChainUserChecker.php';

        return $container->privates['security.user_checker.chain.main'] = new \Symfony\Component\Security\Core\User\ChainUserChecker(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['PHPMaker2026\\Project2\\UserChecker'] ??= new \PHPMaker2026\Project2\UserChecker());
        }, 1));
    }
}
