<?php

namespace ContainerFdodtBX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewPaymentReportControllersearchService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yEu_Fci.PHPMaker2026\Project2\ViewPaymentReportController::search()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['services', 'PHPMaker2026\\Project2\\ViewPaymentReportSearch', 'getViewPaymentReportSearchService', true],
        ], [
            'page' => 'PHPMaker2026\\Project2\\ViewPaymentReportSearch',
        ]))->withContext('PHPMaker2026\\Project2\\ViewPaymentReportController::search()', $container);

        if (isset($container->privates['.service_locator.yEu_Fci.PHPMaker2026\\Project2\\ViewPaymentReportController::search()'])) {
            return $container->privates['.service_locator.yEu_Fci.PHPMaker2026\\Project2\\ViewPaymentReportController::search()'];
        }

        return $container->privates['.service_locator.yEu_Fci.PHPMaker2026\\Project2\\ViewPaymentReportController::search()'] = $instance;
    }
}
