<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3aQxKJ3\PHPMaker2026_Project2_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3aQxKJ3/PHPMaker2026_Project2_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3aQxKJ3.legacy');

    return;
}

if (!\class_exists(PHPMaker2026_Project2_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3aQxKJ3\PHPMaker2026_Project2_KernelDevDebugContainer::class, PHPMaker2026_Project2_KernelDevDebugContainer::class, false);
}

return new \Container3aQxKJ3\PHPMaker2026_Project2_KernelDevDebugContainer([
    'container.build_hash' => '3aQxKJ3',
    'container.build_id' => '581e07e9',
    'container.build_time' => 1774861989,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3aQxKJ3');
