<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK4T1HX8\PHPMaker2026_Project2_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK4T1HX8/PHPMaker2026_Project2_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK4T1HX8.legacy');

    return;
}

if (!\class_exists(PHPMaker2026_Project2_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK4T1HX8\PHPMaker2026_Project2_KernelDevDebugContainer::class, PHPMaker2026_Project2_KernelDevDebugContainer::class, false);
}

return new \ContainerK4T1HX8\PHPMaker2026_Project2_KernelDevDebugContainer([
    'container.build_hash' => 'K4T1HX8',
    'container.build_id' => 'a436375e',
    'container.build_time' => 1774093743,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK4T1HX8');
