<?php

namespace ContainerMYRRgLf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentReportControllerInvokeService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XmLm93f.PHPMaker2026\Project2\AppointmentReportController::__invoke()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'service' => ['services', 'PHPMaker2026\\Project2\\AppointmentReportService', 'getAppointmentReportServiceService', true],
            'page' => ['services', 'PHPMaker2026\\Project2\\AppointmentReportSummary', 'getAppointmentReportSummaryService', true],
        ], [
            'service' => 'PHPMaker2026\\Project2\\AppointmentReportService',
            'page' => 'PHPMaker2026\\Project2\\AppointmentReportSummary',
        ]))->withContext('PHPMaker2026\\Project2\\AppointmentReportController::__invoke()', $container);

        if (isset($container->privates['.service_locator.XmLm93f.PHPMaker2026\\Project2\\AppointmentReportController::__invoke()'])) {
            return $container->privates['.service_locator.XmLm93f.PHPMaker2026\\Project2\\AppointmentReportController::__invoke()'];
        }

        return $container->privates['.service_locator.XmLm93f.PHPMaker2026\\Project2\\AppointmentReportController::__invoke()'] = $instance;
    }
}
