<?php

namespace ContainerMYRRgLf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessDeniedListenerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\EventListener\AccessDeniedListener' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\EventListener\AccessDeniedListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'AccessDeniedListener.php';

        $a = ($container->services['PHPMaker2026\\Project2\\AdvancedSecurity'] ?? self::getAdvancedSecurityService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\EventListener\\AccessDeniedListener'])) {
            return $container->services['PHPMaker2026\\Project2\\EventListener\\AccessDeniedListener'];
        }

        $instance = new \PHPMaker2026\Project2\EventListener\AccessDeniedListener($a);

        if (isset($container->services['PHPMaker2026\\Project2\\EventListener\\AccessDeniedListener'])) {
            return $container->services['PHPMaker2026\\Project2\\EventListener\\AccessDeniedListener'];
        }

        return $container->services['PHPMaker2026\\Project2\\EventListener\\AccessDeniedListener'] = $instance;
    }
}
