<?php

namespace ContainerMYRRgLf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentReportService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\AppointmentReport' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\AppointmentReport
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'BaseDbTable.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ReportTable.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'LookupTableInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'models'.\DIRECTORY_SEPARATOR.'AppointmentReport.php';

        $a = ($container->services['PHPMaker2026\\Project2\\AdvancedSecurity'] ?? self::getAdvancedSecurityService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\AppointmentReport'])) {
            return $container->services['PHPMaker2026\\Project2\\AppointmentReport'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\AppointmentReport'])) {
            return $container->services['PHPMaker2026\\Project2\\AppointmentReport'];
        }

        $instance = new \PHPMaker2026\Project2\AppointmentReport(($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)), $a, ($container->services['ParagonIE\\CSPBuilder\\CSPBuilder'] ?? self::getCSPBuilderService($container)), ($container->services['cache.app'] ?? self::getCache_AppService($container)), ($container->services['PHPMaker2026\\Project2\\FieldFactory'] ?? $container->load('getFieldFactoryService')), $b);

        if (isset($container->services['PHPMaker2026\\Project2\\AppointmentReport'])) {
            return $container->services['PHPMaker2026\\Project2\\AppointmentReport'];
        }

        return $container->services['PHPMaker2026\\Project2\\AppointmentReport'] = $instance;
    }
}
