<?php

namespace ContainerMYRRgLf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportHandlerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\ExportHandler' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\ExportHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ExportHandler.php';

        $a = ($container->services['PHPMaker2026\\Project2\\AdvancedSecurity'] ?? self::getAdvancedSecurityService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\ExportHandler'])) {
            return $container->services['PHPMaker2026\\Project2\\ExportHandler'];
        }

        $instance = new \PHPMaker2026\Project2\ExportHandler($container, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)), $a);

        if (isset($container->services['PHPMaker2026\\Project2\\ExportHandler'])) {
            return $container->services['PHPMaker2026\\Project2\\ExportHandler'];
        }

        return $container->services['PHPMaker2026\\Project2\\ExportHandler'] = $instance;
    }
}
