<?php

namespace ContainerMYRRgLf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikJwtAuthentication_WebToken_NbfValidatorService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'lexik_jwt_authentication.web_token.nbf_validator' shared autowired service.
     *
     * @return \Jose\Component\Checker\NotBeforeChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['lexik_jwt_authentication.web_token.nbf_validator'] = new \Jose\Component\Checker\NotBeforeChecker(($container->privates['clock'] ??= new \Symfony\Component\Clock\Clock()), '30');
    }
}
