<?php

namespace ContainerMYRRgLf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageInterfaceService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wMz3Tov.PHPMaker2026\Project2\PageInterface' shared service.
     *
     * @return \PHPMaker2026\Project2\PageInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wMz3Tov": it references interface "PHPMaker2026\\Project2\\PageInterface" but no such service exists. You should maybe alias this interface to one of these existing services: "PHPMaker2026\\Project2\\AppointmentReportSummary", "PHPMaker2026\\Project2\\ViewAppointmentReportList", "PHPMaker2026\\Project2\\ViewAppointmentReportSearch", "PHPMaker2026\\Project2\\ViewFeedbackReportList", "PHPMaker2026\\Project2\\ViewPatientReportList", "PHPMaker2026\\Project2\\ViewPaymentReportList", "PHPMaker2026\\Project2\\ViewPrescriptionReportList", "PHPMaker2026\\Project2\\ViewPrescriptionReportSearch".');
    }
}
