<?php

namespace ContainerMYRRgLf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWarmupLanguageCacheCommandService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\Command\WarmupLanguageCacheCommand' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\Command\WarmupLanguageCacheCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'WarmupLanguageCacheCommand.php';

        return $container->services['PHPMaker2026\\Project2\\Command\\WarmupLanguageCacheCommand'] = new \PHPMaker2026\Project2\Command\WarmupLanguageCacheCommand(($container->services['PHPMaker2026\\Project2\\LanguageCacheWarmer'] ?? $container->load('getLanguageCacheWarmerService')), $container->targetDir.'');
    }
}
