<?php

namespace Container4QBynsx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditTrailFailureSubscriberService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\EventSubscriber\AuditTrailFailureSubscriber' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\EventSubscriber\AuditTrailFailureSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'AuditTrailFailureSubscriber.php';

        return $container->services['PHPMaker2026\\Project2\\EventSubscriber\\AuditTrailFailureSubscriber'] = new \PHPMaker2026\Project2\EventSubscriber\AuditTrailFailureSubscriber(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->services['PHPMaker2026\\Project2\\AppServiceLocator'] ?? self::getAppServiceLocatorService($container)), ($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)));
    }
}
