<?php

namespace Container4QBynsx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConnectionMiddlewareService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\ConnectionMiddleware' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\ConnectionMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PHPMaker2026\\Project2\\ConnectionMiddleware'] = new \PHPMaker2026\Project2\ConnectionMiddleware();
    }
}
