<?php

namespace Container4QBynsx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEsmtpTransportFactoryDecoratorService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\EsmtpTransportFactoryDecorator' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\EsmtpTransportFactoryDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Transport'.\DIRECTORY_SEPARATOR.'TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EsmtpTransportFactoryDecorator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Transport'.\DIRECTORY_SEPARATOR.'AbstractTransportFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Transport'.\DIRECTORY_SEPARATOR.'Smtp'.\DIRECTORY_SEPARATOR.'EsmtpTransportFactory.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\EsmtpTransportFactoryDecorator'])) {
            return $container->services['PHPMaker2026\\Project2\\EsmtpTransportFactoryDecorator'];
        }

        $instance = new \PHPMaker2026\Project2\EsmtpTransportFactoryDecorator(new \Symfony\Component\Mailer\Transport\Smtp\EsmtpTransportFactory($a, ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['monolog.logger.mailer'] ?? $container->load('getMonolog_Logger_MailerService'))), ['SERVER' => $container->getEnv('SMTP_SERVER'), 'SERVER_PORT' => $container->getEnv('int:SMTP_SERVER_PORT'), 'SERVER_USERNAME' => $container->getEnv('SMTP_SERVER_USERNAME'), 'SERVER_PASSWORD' => $container->getEnv('SMTP_SERVER_PASSWORD'), 'SECURE_OPTION' => $container->getEnv('SMTP_SECURE_OPTION'), 'OPTIONS' => $container->getEnv('SMTP_OPTIONS')], []);

        if (isset($container->services['PHPMaker2026\\Project2\\EsmtpTransportFactoryDecorator'])) {
            return $container->services['PHPMaker2026\\Project2\\EsmtpTransportFactoryDecorator'];
        }

        return $container->services['PHPMaker2026\\Project2\\EsmtpTransportFactoryDecorator'] = $instance;
    }
}
