<?php

namespace Container4QBynsx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifierService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private 'notifier' shared service.
     *
     * @return \Symfony\Component\Notifier\Notifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'notifier'.\DIRECTORY_SEPARATOR.'NotifierInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'notifier'.\DIRECTORY_SEPARATOR.'Notifier.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'notifier'.\DIRECTORY_SEPARATOR.'Channel'.\DIRECTORY_SEPARATOR.'ChannelPolicyInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'notifier'.\DIRECTORY_SEPARATOR.'Channel'.\DIRECTORY_SEPARATOR.'ChannelPolicy.php';

        $instance = new \Symfony\Component\Notifier\Notifier(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'browser' => ['privates', 'notifier.channel.browser', 'getNotifier_Channel_BrowserService', true],
            'chat' => ['privates', 'notifier.channel.chat', 'getNotifier_Channel_ChatService', true],
            'sms' => ['privates', 'notifier.channel.sms', 'getNotifier_Channel_SmsService', true],
            'email' => ['privates', 'notifier.channel.email', 'getNotifier_Channel_EmailService', true],
            'push' => ['privates', 'notifier.channel.push', 'getNotifier_Channel_PushService', true],
            'desktop' => ['privates', 'notifier.channel.desktop', 'getNotifier_Channel_DesktopService', true],
        ], [
            'browser' => 'Symfony\\Component\\Notifier\\Channel\\BrowserChannel',
            'chat' => 'Symfony\\Component\\Notifier\\Channel\\ChatChannel',
            'sms' => 'Symfony\\Component\\Notifier\\Channel\\SmsChannel',
            'email' => 'Symfony\\Component\\Notifier\\Channel\\EmailChannel',
            'push' => 'Symfony\\Component\\Notifier\\Channel\\PushChannel',
            'desktop' => 'Symfony\\Component\\Notifier\\Channel\\DesktopChannel',
        ]), new \Symfony\Component\Notifier\Channel\ChannelPolicy([]));

        if (isset($container->privates['notifier'])) {
            return $container->privates['notifier'];
        }

        return $container->privates['notifier'] = $instance;
    }
}
