<?php

namespace Container4QBynsx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPermissionVoter2Service extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.debug.security.voter.PHPMaker2026\Project2\PermissionVoter' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'Authorization'.\DIRECTORY_SEPARATOR.'Voter'.\DIRECTORY_SEPARATOR.'VoterInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'Authorization'.\DIRECTORY_SEPARATOR.'Voter'.\DIRECTORY_SEPARATOR.'CacheableVoterInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'Authorization'.\DIRECTORY_SEPARATOR.'Voter'.\DIRECTORY_SEPARATOR.'TraceableVoter.php';

        $a = ($container->services['PHPMaker2026\\Project2\\PermissionVoter'] ?? $container->load('getPermissionVoterService'));

        if (isset($container->privates['.debug.security.voter.PHPMaker2026\\Project2\\PermissionVoter'])) {
            return $container->privates['.debug.security.voter.PHPMaker2026\\Project2\\PermissionVoter'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['.debug.security.voter.PHPMaker2026\\Project2\\PermissionVoter'])) {
            return $container->privates['.debug.security.voter.PHPMaker2026\\Project2\\PermissionVoter'];
        }

        $instance = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter($a, $b);

        if (isset($container->privates['.debug.security.voter.PHPMaker2026\\Project2\\PermissionVoter'])) {
            return $container->privates['.debug.security.voter.PHPMaker2026\\Project2\\PermissionVoter'];
        }

        return $container->privates['.debug.security.voter.PHPMaker2026\\Project2\\PermissionVoter'] = $instance;
    }
}
