<?php

namespace Container4QBynsx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewFeedbackReportControllerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\ViewFeedbackReportController' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\ViewFeedbackReportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'BaseController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'controllers'.\DIRECTORY_SEPARATOR.'ViewFeedbackReportController.php';

        return $container->services['PHPMaker2026\\Project2\\ViewFeedbackReportController'] = new \PHPMaker2026\Project2\ViewFeedbackReportController(($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)), ($container->services['PHPMaker2026\\Project2\\AdvancedSecurity'] ?? self::getAdvancedSecurityService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['PHPMaker2026\\Project2\\PhpRenderer'] ??= new \PHPMaker2026\Project2\PhpRenderer('views/')), ($container->privates['twig'] ?? self::getTwigService($container)), ($container->services['PHPMaker2026\\Project2\\RuntimeLinkProvider'] ?? $container->load('getRuntimeLinkProviderService')), ($container->services['PHPMaker2026\\Project2\\AppServiceLocator'] ?? self::getAppServiceLocatorService($container)), ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)), ($container->services['http_kernel'] ?? self::getHttpKernelService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
