<?php

namespace ContainerQY7Emsa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VXDTPcr_KernelsetHttpContextService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VXDTPcr.kernel::setHttpContext()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VXDTPcr.kernel::setHttpContext()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'httpContext' => ['privates', '.errored..service_locator.VXDTPcr.PHPMaker2026\\Project2\\HttpContext', NULL, 'Cannot autowire service ".service_locator.VXDTPcr": it references class "PHPMaker2026\\Project2\\HttpContext" but no such service exists.'],
        ], [
            'httpContext' => 'PHPMaker2026\\Project2\\HttpContext',
        ]))->withContext('kernel::setHttpContext()', $container);
    }
}
