<?php

namespace ContainerQY7Emsa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineEventListenerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\EventListener\DoctrineEventListener' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\EventListener\DoctrineEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'DoctrineEventListener.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\EventListener\\DoctrineEventListener'])) {
            return $container->services['PHPMaker2026\\Project2\\EventListener\\DoctrineEventListener'];
        }

        $instance = new \PHPMaker2026\Project2\EventListener\DoctrineEventListener($a);

        if (isset($container->services['PHPMaker2026\\Project2\\EventListener\\DoctrineEventListener'])) {
            return $container->services['PHPMaker2026\\Project2\\EventListener\\DoctrineEventListener'];
        }

        return $container->services['PHPMaker2026\\Project2\\EventListener\\DoctrineEventListener'] = $instance;
    }
}
