<?php

namespace ContainerQY7Emsa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_DBListeners_AttachEntityListenersService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine.orm.DB_listeners.attach_entity_listeners' shared service.
     *
     * @return \Doctrine\ORM\Tools\AttachEntityListenersListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'doctrine'.\DIRECTORY_SEPARATOR.'orm'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Tools'.\DIRECTORY_SEPARATOR.'AttachEntityListenersListener.php';

        $container->privates['doctrine.orm.DB_listeners.attach_entity_listeners'] = $instance = new \Doctrine\ORM\Tools\AttachEntityListenersListener();

        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\RefundTbl', 'PHPMaker2026\\Project2\\RefundTbl', 'postPersist', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\RefundTbl', 'PHPMaker2026\\Project2\\RefundTbl', 'postUpdate', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\RefundTbl', 'PHPMaker2026\\Project2\\RefundTbl', 'postRemove', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\RefundTbl', 'PHPMaker2026\\Project2\\RefundTbl', 'postPersist', 'updateLastInsertId');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\RefundTbl', 'PHPMaker2026\\Project2\\RefundTbl', 'preUpdate', 'preUpdate');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewAppointmentReport', 'PHPMaker2026\\Project2\\ViewAppointmentReport', 'postPersist', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewAppointmentReport', 'PHPMaker2026\\Project2\\ViewAppointmentReport', 'postUpdate', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewAppointmentReport', 'PHPMaker2026\\Project2\\ViewAppointmentReport', 'postRemove', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewAppointmentReport', 'PHPMaker2026\\Project2\\ViewAppointmentReport', 'postPersist', 'updateLastInsertId');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewAppointmentReport', 'PHPMaker2026\\Project2\\ViewAppointmentReport', 'preUpdate', 'preUpdate');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewDoctorReport', 'PHPMaker2026\\Project2\\ViewDoctorReport', 'postPersist', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewDoctorReport', 'PHPMaker2026\\Project2\\ViewDoctorReport', 'postUpdate', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewDoctorReport', 'PHPMaker2026\\Project2\\ViewDoctorReport', 'postRemove', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewDoctorReport', 'PHPMaker2026\\Project2\\ViewDoctorReport', 'postPersist', 'updateLastInsertId');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewDoctorReport', 'PHPMaker2026\\Project2\\ViewDoctorReport', 'preUpdate', 'preUpdate');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewFeedbackReport', 'PHPMaker2026\\Project2\\ViewFeedbackReport', 'postPersist', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewFeedbackReport', 'PHPMaker2026\\Project2\\ViewFeedbackReport', 'postUpdate', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewFeedbackReport', 'PHPMaker2026\\Project2\\ViewFeedbackReport', 'postRemove', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewFeedbackReport', 'PHPMaker2026\\Project2\\ViewFeedbackReport', 'postPersist', 'updateLastInsertId');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewFeedbackReport', 'PHPMaker2026\\Project2\\ViewFeedbackReport', 'preUpdate', 'preUpdate');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPatientReport', 'PHPMaker2026\\Project2\\ViewPatientReport', 'postPersist', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPatientReport', 'PHPMaker2026\\Project2\\ViewPatientReport', 'postUpdate', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPatientReport', 'PHPMaker2026\\Project2\\ViewPatientReport', 'postRemove', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPatientReport', 'PHPMaker2026\\Project2\\ViewPatientReport', 'postPersist', 'updateLastInsertId');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPatientReport', 'PHPMaker2026\\Project2\\ViewPatientReport', 'preUpdate', 'preUpdate');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPaymentReport', 'PHPMaker2026\\Project2\\ViewPaymentReport', 'postPersist', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPaymentReport', 'PHPMaker2026\\Project2\\ViewPaymentReport', 'postUpdate', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPaymentReport', 'PHPMaker2026\\Project2\\ViewPaymentReport', 'postRemove', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPaymentReport', 'PHPMaker2026\\Project2\\ViewPaymentReport', 'postPersist', 'updateLastInsertId');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPaymentReport', 'PHPMaker2026\\Project2\\ViewPaymentReport', 'preUpdate', 'preUpdate');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPrescriptionReport', 'PHPMaker2026\\Project2\\ViewPrescriptionReport', 'postPersist', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPrescriptionReport', 'PHPMaker2026\\Project2\\ViewPrescriptionReport', 'postUpdate', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPrescriptionReport', 'PHPMaker2026\\Project2\\ViewPrescriptionReport', 'postRemove', 'clearCache');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPrescriptionReport', 'PHPMaker2026\\Project2\\ViewPrescriptionReport', 'postPersist', 'updateLastInsertId');
        $instance->addEntityListener('PHPMaker2026\\Project2\\Db\\Entity\\ViewPrescriptionReport', 'PHPMaker2026\\Project2\\ViewPrescriptionReport', 'preUpdate', 'preUpdate');

        return $instance;
    }
}
