<?php

namespace ContainerQY7Emsa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageManagerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\ImageManager' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\ImageManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ImageManager.php';

        return $container->services['PHPMaker2026\\Project2\\ImageManager'] = new \PHPMaker2026\Project2\ImageManager('Intervention\\Image\\Drivers\\Gd\\Driver', 100, true, false);
    }
}
