<?php

namespace ContainerQY7Emsa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJwtListenerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\EventListener\JwtListener' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\EventListener\JwtListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'JwtListener.php';

        $a = ($container->services['PHPMaker2026\\Project2\\UserProfile'] ?? self::getUserProfileService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\EventListener\\JwtListener'])) {
            return $container->services['PHPMaker2026\\Project2\\EventListener\\JwtListener'];
        }
        $b = ($container->services['PHPMaker2026\\Project2\\AdvancedSecurity'] ?? self::getAdvancedSecurityService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\EventListener\\JwtListener'])) {
            return $container->services['PHPMaker2026\\Project2\\EventListener\\JwtListener'];
        }

        $instance = new \PHPMaker2026\Project2\EventListener\JwtListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, $b, ($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)));

        if (isset($container->services['PHPMaker2026\\Project2\\EventListener\\JwtListener'])) {
            return $container->services['PHPMaker2026\\Project2\\EventListener\\JwtListener'];
        }

        return $container->services['PHPMaker2026\\Project2\\EventListener\\JwtListener'] = $instance;
    }
}
