<?php

namespace ContainerQY7Emsa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageCacheWarmerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\LanguageCacheWarmer' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\LanguageCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'CacheWarmer'.\DIRECTORY_SEPARATOR.'CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'LanguageCacheWarmer.php';

        return $container->services['PHPMaker2026\\Project2\\LanguageCacheWarmer'] = new \PHPMaker2026\Project2\LanguageCacheWarmer(($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), (\dirname(__DIR__, 4).'/lang'));
    }
}
