<?php

namespace ContainerQY7Emsa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMiddlewareService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'Firehed\DbalLogger\Middleware' shared autowired service.
     *
     * @return \Firehed\DbalLogger\Middleware
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Firehed\\DbalLogger\\Middleware'] = new \Firehed\DbalLogger\Middleware(($container->services['PHPMaker2026\\Project2\\DebugStack'] ?? self::getDebugStackService($container)));
    }
}
