<?php

namespace ContainerQY7Emsa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundTblControllerlistService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ywGGMP8.PHPMaker2026\Project2\RefundTblController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['services', 'PHPMaker2026\\Project2\\RefundTblList', 'getRefundTblListService', true],
        ], [
            'page' => 'PHPMaker2026\\Project2\\RefundTblList',
        ]))->withContext('PHPMaker2026\\Project2\\RefundTblController::list()', $container);

        if (isset($container->privates['.service_locator.ywGGMP8.PHPMaker2026\\Project2\\RefundTblController::list()'])) {
            return $container->privates['.service_locator.ywGGMP8.PHPMaker2026\\Project2\\RefundTblController::list()'];
        }

        return $container->privates['.service_locator.ywGGMP8.PHPMaker2026\\Project2\\RefundTblController::list()'] = $instance;
    }
}
