<?php

namespace ContainerQY7Emsa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundTblControllerviewService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9AI0qsY.PHPMaker2026\Project2\RefundTblController::view()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['services', 'PHPMaker2026\\Project2\\RefundTblView', 'getRefundTblViewService', true],
        ], [
            'page' => 'PHPMaker2026\\Project2\\RefundTblView',
        ]))->withContext('PHPMaker2026\\Project2\\RefundTblController::view()', $container);

        if (isset($container->privates['.service_locator.9AI0qsY.PHPMaker2026\\Project2\\RefundTblController::view()'])) {
            return $container->privates['.service_locator.9AI0qsY.PHPMaker2026\\Project2\\RefundTblController::view()'];
        }

        return $container->privates['.service_locator.9AI0qsY.PHPMaker2026\\Project2\\RefundTblController::view()'] = $instance;
    }
}
