<?php

namespace ContainerQY7Emsa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewAppointmentReportControllersearchService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8Sc5o65.PHPMaker2026\Project2\ViewAppointmentReportController::search()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['services', 'PHPMaker2026\\Project2\\ViewAppointmentReportSearch', 'getViewAppointmentReportSearchService', true],
        ], [
            'page' => 'PHPMaker2026\\Project2\\ViewAppointmentReportSearch',
        ]))->withContext('PHPMaker2026\\Project2\\ViewAppointmentReportController::search()', $container);

        if (isset($container->privates['.service_locator.8Sc5o65.PHPMaker2026\\Project2\\ViewAppointmentReportController::search()'])) {
            return $container->privates['.service_locator.8Sc5o65.PHPMaker2026\\Project2\\ViewAppointmentReportController::search()'];
        }

        return $container->privates['.service_locator.8Sc5o65.PHPMaker2026\\Project2\\ViewAppointmentReportController::search()'] = $instance;
    }
}
