<?php

namespace ContainerQY7Emsa;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewPrescriptionReportControllersearchService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JoDynSJ.PHPMaker2026\Project2\ViewPrescriptionReportController::search()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['services', 'PHPMaker2026\\Project2\\ViewPrescriptionReportSearch', 'getViewPrescriptionReportSearchService', true],
        ], [
            'page' => 'PHPMaker2026\\Project2\\ViewPrescriptionReportSearch',
        ]))->withContext('PHPMaker2026\\Project2\\ViewPrescriptionReportController::search()', $container);

        if (isset($container->privates['.service_locator.JoDynSJ.PHPMaker2026\\Project2\\ViewPrescriptionReportController::search()'])) {
            return $container->privates['.service_locator.JoDynSJ.PHPMaker2026\\Project2\\ViewPrescriptionReportController::search()'];
        }

        return $container->privates['.service_locator.JoDynSJ.PHPMaker2026\\Project2\\ViewPrescriptionReportController::search()'] = $instance;
    }
}
