<?php

namespace ContainerJw01ix8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCascadeUpdateDeleteListenerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\EventListener\CascadeUpdateDeleteListener' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\EventListener\CascadeUpdateDeleteListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'CascadeUpdateDeleteListener.php';

        $a = ($container->services['PHPMaker2026\\Project2\\AppServiceLocator'] ?? self::getAppServiceLocatorService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\EventListener\\CascadeUpdateDeleteListener'])) {
            return $container->services['PHPMaker2026\\Project2\\EventListener\\CascadeUpdateDeleteListener'];
        }

        $instance = new \PHPMaker2026\Project2\EventListener\CascadeUpdateDeleteListener(($container->services['doctrine'] ?? self::getDoctrineService($container)), $a, ($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)), []);

        if (isset($container->services['PHPMaker2026\\Project2\\EventListener\\CascadeUpdateDeleteListener'])) {
            return $container->services['PHPMaker2026\\Project2\\EventListener\\CascadeUpdateDeleteListener'];
        }

        return $container->services['PHPMaker2026\\Project2\\EventListener\\CascadeUpdateDeleteListener'] = $instance;
    }
}
