<?php

namespace ContainerJw01ix8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChartRendererInterfaceService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\ChartRendererInterface' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\ChartJsRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ChartRendererInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ChartJsRenderer.php';

        return $container->services['PHPMaker2026\\Project2\\ChartRendererInterface'] = new \PHPMaker2026\Project2\ChartJsRenderer();
    }
}
