<?php

namespace ContainerJw01ix8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOriginalEntitiesResolverService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\OriginalEntitiesResolver' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\OriginalEntitiesResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'OriginalEntitiesResolver.php';

        $a = ($container->services['PHPMaker2026\\Project2\\AppServiceLocator'] ?? self::getAppServiceLocatorService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\OriginalEntitiesResolver'])) {
            return $container->services['PHPMaker2026\\Project2\\OriginalEntitiesResolver'];
        }

        $instance = new \PHPMaker2026\Project2\OriginalEntitiesResolver(($container->services['doctrine'] ?? self::getDoctrineService($container)), $a);

        if (isset($container->services['PHPMaker2026\\Project2\\OriginalEntitiesResolver'])) {
            return $container->services['PHPMaker2026\\Project2\\OriginalEntitiesResolver'];
        }

        return $container->services['PHPMaker2026\\Project2\\OriginalEntitiesResolver'] = $instance;
    }
}
