<?php

namespace ContainerJw01ix8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPsrServerRequestResolverService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'Symfony\Bridge\PsrHttpMessage\ArgumentValueResolver\PsrServerRequestResolver' shared autowired service.
     *
     * @return \Symfony\Bridge\PsrHttpMessage\ArgumentValueResolver\PsrServerRequestResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'psr-http-message-bridge'.\DIRECTORY_SEPARATOR.'ArgumentValueResolver'.\DIRECTORY_SEPARATOR.'PsrServerRequestResolver.php';

        return $container->services['Symfony\\Bridge\\PsrHttpMessage\\ArgumentValueResolver\\PsrServerRequestResolver'] = new \Symfony\Bridge\PsrHttpMessage\ArgumentValueResolver\PsrServerRequestResolver(($container->services['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $container->load('getPsrHttpFactoryService')));
    }
}
