<?php

namespace ContainerJw01ix8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewDoctorReportControllerlistService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gQniC2p.PHPMaker2026\Project2\ViewDoctorReportController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['services', 'PHPMaker2026\\Project2\\ViewDoctorReportList', 'getViewDoctorReportListService', true],
        ], [
            'page' => 'PHPMaker2026\\Project2\\ViewDoctorReportList',
        ]))->withContext('PHPMaker2026\\Project2\\ViewDoctorReportController::list()', $container);

        if (isset($container->privates['.service_locator.gQniC2p.PHPMaker2026\\Project2\\ViewDoctorReportController::list()'])) {
            return $container->privates['.service_locator.gQniC2p.PHPMaker2026\\Project2\\ViewDoctorReportController::list()'];
        }

        return $container->privates['.service_locator.gQniC2p.PHPMaker2026\\Project2\\ViewDoctorReportController::list()'] = $instance;
    }
}
