<?php

namespace Proxies\__CG__\PHPMaker2026\Project2\Db\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RefundTbl extends \PHPMaker2026\Project2\Db\Entity\RefundTbl implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'classMetadata' => [parent::class, 'classMetadata', null, 8],
        "\0".'*'."\0".'fieldNames' => [parent::class, 'fieldNames', null, 8],
        "\0".parent::class."\0".'appointmentId' => [parent::class, 'appointmentId', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'patientId' => [parent::class, 'patientId', null, 16],
        "\0".parent::class."\0".'paymentId' => [parent::class, 'paymentId', null, 16],
        "\0".parent::class."\0".'refundAmount' => [parent::class, 'refundAmount', null, 16],
        "\0".parent::class."\0".'refundDate' => [parent::class, 'refundDate', null, 16],
        "\0".parent::class."\0".'refundId' => [parent::class, 'refundId', null, 16],
        "\0".parent::class."\0".'refundReason' => [parent::class, 'refundReason', null, 16],
        "\0".parent::class."\0".'refundStatus' => [parent::class, 'refundStatus', null, 16],
        "\0".parent::class."\0".'refundTxnId' => [parent::class, 'refundTxnId', null, 16],
        'appointmentId' => [parent::class, 'appointmentId', null, 16],
        'classMetadata' => [parent::class, 'classMetadata', null, 8],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'fieldNames' => [parent::class, 'fieldNames', null, 8],
        'patientId' => [parent::class, 'patientId', null, 16],
        'paymentId' => [parent::class, 'paymentId', null, 16],
        'refundAmount' => [parent::class, 'refundAmount', null, 16],
        'refundDate' => [parent::class, 'refundDate', null, 16],
        'refundId' => [parent::class, 'refundId', null, 16],
        'refundReason' => [parent::class, 'refundReason', null, 16],
        'refundStatus' => [parent::class, 'refundStatus', null, 16],
        'refundTxnId' => [parent::class, 'refundTxnId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = parent::__serialize();
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
