<?php

namespace Proxies\__CG__\PHPMaker2026\Project2\Db\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ViewAppointmentReport extends \PHPMaker2026\Project2\Db\Entity\ViewAppointmentReport implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'classMetadata' => [parent::class, 'classMetadata', null, 8],
        "\0".'*'."\0".'fieldNames' => [parent::class, 'fieldNames', null, 8],
        "\0".parent::class."\0".'appointmentDate' => [parent::class, 'appointmentDate', null, 16],
        "\0".parent::class."\0".'appointmentId' => [parent::class, 'appointmentId', null, 16],
        "\0".parent::class."\0".'appointmentTime' => [parent::class, 'appointmentTime', null, 16],
        "\0".parent::class."\0".'dayName' => [parent::class, 'dayName', null, 16],
        "\0".parent::class."\0".'doctorName' => [parent::class, 'doctorName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'monthName' => [parent::class, 'monthName', null, 16],
        "\0".parent::class."\0".'monthNumber' => [parent::class, 'monthNumber', null, 16],
        "\0".parent::class."\0".'patientName' => [parent::class, 'patientName', null, 16],
        "\0".parent::class."\0".'specialisation' => [parent::class, 'specialisation', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'weekNumber' => [parent::class, 'weekNumber', null, 16],
        "\0".parent::class."\0".'year' => [parent::class, 'year', null, 16],
        'appointmentDate' => [parent::class, 'appointmentDate', null, 16],
        'appointmentId' => [parent::class, 'appointmentId', null, 16],
        'appointmentTime' => [parent::class, 'appointmentTime', null, 16],
        'classMetadata' => [parent::class, 'classMetadata', null, 8],
        'dayName' => [parent::class, 'dayName', null, 16],
        'doctorName' => [parent::class, 'doctorName', null, 16],
        'fieldNames' => [parent::class, 'fieldNames', null, 8],
        'id' => [parent::class, 'id', null, 16],
        'monthName' => [parent::class, 'monthName', null, 16],
        'monthNumber' => [parent::class, 'monthNumber', null, 16],
        'patientName' => [parent::class, 'patientName', null, 16],
        'specialisation' => [parent::class, 'specialisation', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'weekNumber' => [parent::class, 'weekNumber', null, 16],
        'year' => [parent::class, 'year', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = parent::__serialize();
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
