<?php

namespace Proxies\__CG__\PHPMaker2026\Project2\Db\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AppointmentReport extends \PHPMaker2026\Project2\Db\Entity\AppointmentReport implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'classMetadata' => [parent::class, 'classMetadata', null, 8],
        "\0".'*'."\0".'fieldNames' => [parent::class, 'fieldNames', null, 8],
        "\0".parent::class."\0".'appointmentDate' => [parent::class, 'appointmentDate', null, 16],
        "\0".parent::class."\0".'appointmentId' => [parent::class, 'appointmentId', null, 16],
        "\0".parent::class."\0".'appointmentTime' => [parent::class, 'appointmentTime', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'doctorId' => [parent::class, 'doctorId', null, 16],
        "\0".parent::class."\0".'patientId' => [parent::class, 'patientId', null, 16],
        "\0".parent::class."\0".'scheduleId' => [parent::class, 'scheduleId', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        'appointmentDate' => [parent::class, 'appointmentDate', null, 16],
        'appointmentId' => [parent::class, 'appointmentId', null, 16],
        'appointmentTime' => [parent::class, 'appointmentTime', null, 16],
        'classMetadata' => [parent::class, 'classMetadata', null, 8],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'doctorId' => [parent::class, 'doctorId', null, 16],
        'fieldNames' => [parent::class, 'fieldNames', null, 8],
        'patientId' => [parent::class, 'patientId', null, 16],
        'scheduleId' => [parent::class, 'scheduleId', null, 16],
        'status' => [parent::class, 'status', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = parent::__serialize();
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
