<?php

namespace Proxies\__CG__\PHPMaker2026\Project2\Db\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ViewPatientReport extends \PHPMaker2026\Project2\Db\Entity\ViewPatientReport implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'classMetadata' => [parent::class, 'classMetadata', null, 8],
        "\0".'*'."\0".'fieldNames' => [parent::class, 'fieldNames', null, 8],
        "\0".parent::class."\0".'avgRatingGiven' => [parent::class, 'avgRatingGiven', null, 16],
        "\0".parent::class."\0".'bloodGroup' => [parent::class, 'bloodGroup', null, 16],
        "\0".parent::class."\0".'cancelledAppointments' => [parent::class, 'cancelledAppointments', null, 16],
        "\0".parent::class."\0".'completedAppointments' => [parent::class, 'completedAppointments', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'firstVisit' => [parent::class, 'firstVisit', null, 16],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lastVisit' => [parent::class, 'lastVisit', null, 16],
        "\0".parent::class."\0".'patientId' => [parent::class, 'patientId', null, 16],
        "\0".parent::class."\0".'patientName' => [parent::class, 'patientName', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'totalAmountPaid' => [parent::class, 'totalAmountPaid', null, 16],
        "\0".parent::class."\0".'totalAppointments' => [parent::class, 'totalAppointments', null, 16],
        "\0".parent::class."\0".'totalPrescriptions' => [parent::class, 'totalPrescriptions', null, 16],
        "\0".parent::class."\0".'upcomingAppointments' => [parent::class, 'upcomingAppointments', null, 16],
        'avgRatingGiven' => [parent::class, 'avgRatingGiven', null, 16],
        'bloodGroup' => [parent::class, 'bloodGroup', null, 16],
        'cancelledAppointments' => [parent::class, 'cancelledAppointments', null, 16],
        'classMetadata' => [parent::class, 'classMetadata', null, 8],
        'completedAppointments' => [parent::class, 'completedAppointments', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'fieldNames' => [parent::class, 'fieldNames', null, 8],
        'firstVisit' => [parent::class, 'firstVisit', null, 16],
        'gender' => [parent::class, 'gender', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lastVisit' => [parent::class, 'lastVisit', null, 16],
        'patientId' => [parent::class, 'patientId', null, 16],
        'patientName' => [parent::class, 'patientName', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'totalAmountPaid' => [parent::class, 'totalAmountPaid', null, 16],
        'totalAppointments' => [parent::class, 'totalAppointments', null, 16],
        'totalPrescriptions' => [parent::class, 'totalPrescriptions', null, 16],
        'upcomingAppointments' => [parent::class, 'upcomingAppointments', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = parent::__serialize();
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
