<?php

namespace Proxies\__CG__\PHPMaker2026\Project2\Db\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ViewDoctorReport extends \PHPMaker2026\Project2\Db\Entity\ViewDoctorReport implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'classMetadata' => [parent::class, 'classMetadata', null, 8],
        "\0".'*'."\0".'fieldNames' => [parent::class, 'fieldNames', null, 8],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        'classMetadata' => [parent::class, 'classMetadata', null, 8],
        'fieldNames' => [parent::class, 'fieldNames', null, 8],
        'id' => [parent::class, 'id', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = parent::__serialize();
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
