<?php

namespace Proxies\__CG__\PHPMaker2026\Project2\Db\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ViewPrescriptionReport extends \PHPMaker2026\Project2\Db\Entity\ViewPrescriptionReport implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'classMetadata' => [parent::class, 'classMetadata', null, 8],
        "\0".'*'."\0".'fieldNames' => [parent::class, 'fieldNames', null, 8],
        "\0".parent::class."\0".'additionalNotes' => [parent::class, 'additionalNotes', null, 16],
        "\0".parent::class."\0".'bloodPressure' => [parent::class, 'bloodPressure', null, 16],
        "\0".parent::class."\0".'diabetes' => [parent::class, 'diabetes', null, 16],
        "\0".parent::class."\0".'diagnosis' => [parent::class, 'diagnosis', null, 16],
        "\0".parent::class."\0".'doctorName' => [parent::class, 'doctorName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'issueDate' => [parent::class, 'issueDate', null, 16],
        "\0".parent::class."\0".'patientName' => [parent::class, 'patientName', null, 16],
        "\0".parent::class."\0".'prescriptionId' => [parent::class, 'prescriptionId', null, 16],
        "\0".parent::class."\0".'specialisation' => [parent::class, 'specialisation', null, 16],
        "\0".parent::class."\0".'symptoms' => [parent::class, 'symptoms', null, 16],
        'additionalNotes' => [parent::class, 'additionalNotes', null, 16],
        'bloodPressure' => [parent::class, 'bloodPressure', null, 16],
        'classMetadata' => [parent::class, 'classMetadata', null, 8],
        'diabetes' => [parent::class, 'diabetes', null, 16],
        'diagnosis' => [parent::class, 'diagnosis', null, 16],
        'doctorName' => [parent::class, 'doctorName', null, 16],
        'fieldNames' => [parent::class, 'fieldNames', null, 8],
        'id' => [parent::class, 'id', null, 16],
        'issueDate' => [parent::class, 'issueDate', null, 16],
        'patientName' => [parent::class, 'patientName', null, 16],
        'prescriptionId' => [parent::class, 'prescriptionId', null, 16],
        'specialisation' => [parent::class, 'specialisation', null, 16],
        'symptoms' => [parent::class, 'symptoms', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = parent::__serialize();
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
