<?php

namespace ContainerQFiGXrB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllerprocessPageService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wMz3Tov.PHPMaker2026\Project2\ApiController::processPage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wMz3Tov.PHPMaker2026\\Project2\\ApiController::processPage()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['privates', '.errored..service_locator.wMz3Tov.PHPMaker2026\\Project2\\PageInterface', NULL, 'Cannot autowire service ".service_locator.wMz3Tov": it references interface "PHPMaker2026\\Project2\\PageInterface" but no such service exists. You should maybe alias this interface to one of these existing services: "PHPMaker2026\\Project2\\AppointmentReportSummary", "PHPMaker2026\\Project2\\ViewAppointmentReportList", "PHPMaker2026\\Project2\\ViewAppointmentReportSearch", "PHPMaker2026\\Project2\\ViewFeedbackReportList", "PHPMaker2026\\Project2\\ViewPatientReportList", "PHPMaker2026\\Project2\\ViewPaymentReportList", "PHPMaker2026\\Project2\\ViewPaymentReportSearch", "PHPMaker2026\\Project2\\ViewPrescriptionReportList", "PHPMaker2026\\Project2\\ViewPrescriptionReportSearch".'],
        ], [
            'page' => 'PHPMaker2026\\Project2\\PageInterface',
        ]))->withContext('PHPMaker2026\\Project2\\ApiController::processPage()', $container);
    }
}
