<?php

namespace ContainerQFiGXrB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ArgumentResolver'.\DIRECTORY_SEPARATOR.'ServiceValueResolver.php';

        $instance = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::setHttpContext' => ['privates', '.service_locator.VXDTPcr.kernel::setHttpContext()', 'get_ServiceLocator_VXDTPcr_KernelsetHttpContextService', true],
            'PHPMaker2026\\Project2\\Kernel::setHttpContext' => ['privates', '.service_locator.VXDTPcr.kernel::setHttpContext()', 'get_ServiceLocator_VXDTPcr_KernelsetHttpContextService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'PHPMaker2026\\Project2\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'PHPMaker2026\\Project2\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'PHPMaker2026\\Project2\\ApiController::processPage' => ['privates', '.service_locator.wMz3Tov.PHPMaker2026\\Project2\\ApiController::processPage()', 'getApiControllerprocessPageService', true],
            'PHPMaker2026\\Project2\\AppointmentReportController::__invoke' => ['privates', '.service_locator.XmLm93f.PHPMaker2026\\Project2\\AppointmentReportController::__invoke()', 'getAppointmentReportControllerInvokeService', true],
            'PHPMaker2026\\Project2\\ViewAppointmentReportController::list' => ['privates', '.service_locator.EfXVwpA.PHPMaker2026\\Project2\\ViewAppointmentReportController::list()', 'getViewAppointmentReportControllerlistService', true],
            'PHPMaker2026\\Project2\\ViewAppointmentReportController::search' => ['privates', '.service_locator.8Sc5o65.PHPMaker2026\\Project2\\ViewAppointmentReportController::search()', 'getViewAppointmentReportControllersearchService', true],
            'PHPMaker2026\\Project2\\ViewFeedbackReportController::list' => ['privates', '.service_locator.nkpZtrq.PHPMaker2026\\Project2\\ViewFeedbackReportController::list()', 'getViewFeedbackReportControllerlistService', true],
            'PHPMaker2026\\Project2\\ViewPatientReportController::list' => ['privates', '.service_locator.e.bQX.a.PHPMaker2026\\Project2\\ViewPatientReportController::list()', 'getViewPatientReportControllerlistService', true],
            'PHPMaker2026\\Project2\\ViewPaymentReportController::list' => ['privates', '.service_locator.BqnqZUP.PHPMaker2026\\Project2\\ViewPaymentReportController::list()', 'getViewPaymentReportControllerlistService', true],
            'PHPMaker2026\\Project2\\ViewPaymentReportController::search' => ['privates', '.service_locator.yEu_Fci.PHPMaker2026\\Project2\\ViewPaymentReportController::search()', 'getViewPaymentReportControllersearchService', true],
            'PHPMaker2026\\Project2\\ViewPrescriptionReportController::list' => ['privates', '.service_locator.rgYL3eR.PHPMaker2026\\Project2\\ViewPrescriptionReportController::list()', 'getViewPrescriptionReportControllerlistService', true],
            'PHPMaker2026\\Project2\\ViewPrescriptionReportController::search' => ['privates', '.service_locator.JoDynSJ.PHPMaker2026\\Project2\\ViewPrescriptionReportController::search()', 'getViewPrescriptionReportControllersearchService', true],
            'kernel:setHttpContext' => ['privates', '.service_locator.VXDTPcr.kernel::setHttpContext()', 'get_ServiceLocator_VXDTPcr_KernelsetHttpContextService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'PHPMaker2026\\Project2\\ApiController:processPage' => ['privates', '.service_locator.wMz3Tov.PHPMaker2026\\Project2\\ApiController::processPage()', 'getApiControllerprocessPageService', true],
            'PHPMaker2026\\Project2\\AppointmentReportController:__invoke' => ['privates', '.service_locator.XmLm93f.PHPMaker2026\\Project2\\AppointmentReportController::__invoke()', 'getAppointmentReportControllerInvokeService', true],
            'PHPMaker2026\\Project2\\AppointmentReportController' => ['privates', '.service_locator.XmLm93f.PHPMaker2026\\Project2\\AppointmentReportController::__invoke()', 'getAppointmentReportControllerInvokeService', true],
            'PHPMaker2026\\Project2\\ViewAppointmentReportController:list' => ['privates', '.service_locator.EfXVwpA.PHPMaker2026\\Project2\\ViewAppointmentReportController::list()', 'getViewAppointmentReportControllerlistService', true],
            'PHPMaker2026\\Project2\\ViewAppointmentReportController:search' => ['privates', '.service_locator.8Sc5o65.PHPMaker2026\\Project2\\ViewAppointmentReportController::search()', 'getViewAppointmentReportControllersearchService', true],
            'PHPMaker2026\\Project2\\ViewFeedbackReportController:list' => ['privates', '.service_locator.nkpZtrq.PHPMaker2026\\Project2\\ViewFeedbackReportController::list()', 'getViewFeedbackReportControllerlistService', true],
            'PHPMaker2026\\Project2\\ViewPatientReportController:list' => ['privates', '.service_locator.e.bQX.a.PHPMaker2026\\Project2\\ViewPatientReportController::list()', 'getViewPatientReportControllerlistService', true],
            'PHPMaker2026\\Project2\\ViewPaymentReportController:list' => ['privates', '.service_locator.BqnqZUP.PHPMaker2026\\Project2\\ViewPaymentReportController::list()', 'getViewPaymentReportControllerlistService', true],
            'PHPMaker2026\\Project2\\ViewPaymentReportController:search' => ['privates', '.service_locator.yEu_Fci.PHPMaker2026\\Project2\\ViewPaymentReportController::search()', 'getViewPaymentReportControllersearchService', true],
            'PHPMaker2026\\Project2\\ViewPrescriptionReportController:list' => ['privates', '.service_locator.rgYL3eR.PHPMaker2026\\Project2\\ViewPrescriptionReportController::list()', 'getViewPrescriptionReportControllerlistService', true],
            'PHPMaker2026\\Project2\\ViewPrescriptionReportController:search' => ['privates', '.service_locator.JoDynSJ.PHPMaker2026\\Project2\\ViewPrescriptionReportController::search()', 'getViewPrescriptionReportControllersearchService', true],
        ], [
            'kernel::setHttpContext' => '?',
            'PHPMaker2026\\Project2\\Kernel::setHttpContext' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'PHPMaker2026\\Project2\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'PHPMaker2026\\Project2\\Kernel::loadRoutes' => '?',
            'PHPMaker2026\\Project2\\ApiController::processPage' => '?',
            'PHPMaker2026\\Project2\\AppointmentReportController::__invoke' => '?',
            'PHPMaker2026\\Project2\\ViewAppointmentReportController::list' => '?',
            'PHPMaker2026\\Project2\\ViewAppointmentReportController::search' => '?',
            'PHPMaker2026\\Project2\\ViewFeedbackReportController::list' => '?',
            'PHPMaker2026\\Project2\\ViewPatientReportController::list' => '?',
            'PHPMaker2026\\Project2\\ViewPaymentReportController::list' => '?',
            'PHPMaker2026\\Project2\\ViewPaymentReportController::search' => '?',
            'PHPMaker2026\\Project2\\ViewPrescriptionReportController::list' => '?',
            'PHPMaker2026\\Project2\\ViewPrescriptionReportController::search' => '?',
            'kernel:setHttpContext' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'PHPMaker2026\\Project2\\ApiController:processPage' => '?',
            'PHPMaker2026\\Project2\\AppointmentReportController:__invoke' => '?',
            'PHPMaker2026\\Project2\\AppointmentReportController' => '?',
            'PHPMaker2026\\Project2\\ViewAppointmentReportController:list' => '?',
            'PHPMaker2026\\Project2\\ViewAppointmentReportController:search' => '?',
            'PHPMaker2026\\Project2\\ViewFeedbackReportController:list' => '?',
            'PHPMaker2026\\Project2\\ViewPatientReportController:list' => '?',
            'PHPMaker2026\\Project2\\ViewPaymentReportController:list' => '?',
            'PHPMaker2026\\Project2\\ViewPaymentReportController:search' => '?',
            'PHPMaker2026\\Project2\\ViewPrescriptionReportController:list' => '?',
            'PHPMaker2026\\Project2\\ViewPrescriptionReportController:search' => '?',
        ]));

        if (isset($container->privates['argument_resolver.service'])) {
            return $container->privates['argument_resolver.service'];
        }

        return $container->privates['argument_resolver.service'] = $instance;
    }
}
