<?php

namespace ContainerQFiGXrB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\ApiController' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\ApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'controllers'.\DIRECTORY_SEPARATOR.'ApiController.php';

        return $container->services['PHPMaker2026\\Project2\\ApiController'] = new \PHPMaker2026\Project2\ApiController(($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)), ($container->services['PHPMaker2026\\Project2\\AdvancedSecurity'] ?? self::getAdvancedSecurityService($container)), ($container->services['PHPMaker2026\\Project2\\AppServiceLocator'] ?? self::getAppServiceLocatorService($container)), ($container->services['PHPMaker2026\\Project2\\UserProfile'] ?? self::getUserProfileService($container)), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
