<?php

namespace ContainerQFiGXrB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefault_Storage_PrefixerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'default.storage.prefixer' shared autowired service.
     *
     * @return \League\Flysystem\PathPrefixer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PathPrefixer.php';

        return $container->services['default.storage.prefixer'] = new \League\Flysystem\PathPrefixer(\dirname(__DIR__, 4), '\\');
    }
}
