<?php

namespace ContainerQFiGXrB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpContextService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VXDTPcr.PHPMaker2026\Project2\HttpContext' shared service.
     *
     * @return \PHPMaker2026\Project2\HttpContext
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VXDTPcr": it references class "PHPMaker2026\\Project2\\HttpContext" but no such service exists.');
    }
}
