<?php

namespace ContainerQFiGXrB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPsrResponseListenerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'Symfony\Bridge\PsrHttpMessage\EventListener\PsrResponseListener' shared autowired service.
     *
     * @return \Symfony\Bridge\PsrHttpMessage\EventListener\PsrResponseListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'psr-http-message-bridge'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'PsrResponseListener.php';

        return $container->services['Symfony\\Bridge\\PsrHttpMessage\\EventListener\\PsrResponseListener'] = new \Symfony\Bridge\PsrHttpMessage\EventListener\PsrResponseListener();
    }
}
