<?php

namespace ContainerQFiGXrB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewPatientReportControllerlistService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e.bQX.a.PHPMaker2026\Project2\ViewPatientReportController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['services', 'PHPMaker2026\\Project2\\ViewPatientReportList', 'getViewPatientReportListService', true],
        ], [
            'page' => 'PHPMaker2026\\Project2\\ViewPatientReportList',
        ]))->withContext('PHPMaker2026\\Project2\\ViewPatientReportController::list()', $container);

        if (isset($container->privates['.service_locator.e.bQX.a.PHPMaker2026\\Project2\\ViewPatientReportController::list()'])) {
            return $container->privates['.service_locator.e.bQX.a.PHPMaker2026\\Project2\\ViewPatientReportController::list()'];
        }

        return $container->privates['.service_locator.e.bQX.a.PHPMaker2026\\Project2\\ViewPatientReportController::list()'] = $instance;
    }
}
