<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJw01ix8\PHPMaker2026_Project2_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJw01ix8/PHPMaker2026_Project2_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJw01ix8.legacy');

    return;
}

if (!\class_exists(PHPMaker2026_Project2_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJw01ix8\PHPMaker2026_Project2_KernelDevDebugContainer::class, PHPMaker2026_Project2_KernelDevDebugContainer::class, false);
}

return new \ContainerJw01ix8\PHPMaker2026_Project2_KernelDevDebugContainer([
    'container.build_hash' => 'Jw01ix8',
    'container.build_id' => 'ff061e6c',
    'container.build_time' => 1774111431,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJw01ix8');
