<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4QBynsx\PHPMaker2026_Project2_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4QBynsx/PHPMaker2026_Project2_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4QBynsx.legacy');

    return;
}

if (!\class_exists(PHPMaker2026_Project2_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4QBynsx\PHPMaker2026_Project2_KernelDevDebugContainer::class, PHPMaker2026_Project2_KernelDevDebugContainer::class, false);
}

return new \Container4QBynsx\PHPMaker2026_Project2_KernelDevDebugContainer([
    'container.build_hash' => '4QBynsx',
    'container.build_id' => '5f92901b',
    'container.build_time' => 1774933361,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4QBynsx');
