<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXtzZZxG\PHPMaker2026_Project2_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXtzZZxG/PHPMaker2026_Project2_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXtzZZxG.legacy');

    return;
}

if (!\class_exists(PHPMaker2026_Project2_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXtzZZxG\PHPMaker2026_Project2_KernelDevDebugContainer::class, PHPMaker2026_Project2_KernelDevDebugContainer::class, false);
}

return new \ContainerXtzZZxG\PHPMaker2026_Project2_KernelDevDebugContainer([
    'container.build_hash' => 'XtzZZxG',
    'container.build_id' => 'a23d5eda',
    'container.build_time' => 1774091791,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXtzZZxG');
