<?php

namespace ContainerJZsQGll;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthenticationSuccessHandlerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\AuthenticationSuccessHandler' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\AuthenticationSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'AuthenticationSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'AuthenticationSuccessHandler.php';

        return $container->services['PHPMaker2026\\Project2\\AuthenticationSuccessHandler'] = new \PHPMaker2026\Project2\AuthenticationSuccessHandler(($container->services['PHPMaker2026\\Project2\\UserProfile'] ?? self::getUserProfileService($container)), ($container->services['PHPMaker2026\\Project2\\AdvancedSecurity'] ?? self::getAdvancedSecurityService($container)), ($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)), ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)));
    }
}
