<?php

namespace ContainerJZsQGll;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConvertLocalEnvToSecretsCommandService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\Command\ConvertLocalEnvToSecretsCommand' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\Command\ConvertLocalEnvToSecretsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ConvertLocalEnvToSecretsCommand.php';

        $container->services['PHPMaker2026\\Project2\\Command\\ConvertLocalEnvToSecretsCommand'] = $instance = new \PHPMaker2026\Project2\Command\ConvertLocalEnvToSecretsCommand(($container->privates['secrets.vault'] ?? $container->load('getSecrets_VaultService')));

        $instance->setName('app:convert-local-secrets');
        $instance->setAliases(['app:convert-local-secrets']);
        $instance->setDescription('Convert selected secrets from .env.<env>.local into the vault and replace them with placeholders');

        return $instance;
    }
}
