<?php

namespace ContainerJZsQGll;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMobile_DetectService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'mobile.detect' shared autowired service.
     *
     * @return \Detection\MobileDetect
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'mobiledetect'.\DIRECTORY_SEPARATOR.'mobiledetectlib'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'MobileDetect.php';

        return $container->services['mobile.detect'] = new \Detection\MobileDetect();
    }
}
