<?php

namespace ContainerJZsQGll;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPermissionVoterService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\PermissionVoter' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\PermissionVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'Authorization'.\DIRECTORY_SEPARATOR.'Voter'.\DIRECTORY_SEPARATOR.'VoterInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'Authorization'.\DIRECTORY_SEPARATOR.'Voter'.\DIRECTORY_SEPARATOR.'CacheableVoterInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'Authorization'.\DIRECTORY_SEPARATOR.'Voter'.\DIRECTORY_SEPARATOR.'Voter.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PermissionVoter.php';

        $a = ($container->services['PHPMaker2026\\Project2\\AdvancedSecurity'] ?? self::getAdvancedSecurityService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\PermissionVoter'])) {
            return $container->services['PHPMaker2026\\Project2\\PermissionVoter'];
        }
        $b = ($container->services['PHPMaker2026\\Project2\\UserProfile'] ?? self::getUserProfileService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\PermissionVoter'])) {
            return $container->services['PHPMaker2026\\Project2\\PermissionVoter'];
        }

        $instance = new \PHPMaker2026\Project2\PermissionVoter(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, $b);

        if (isset($container->services['PHPMaker2026\\Project2\\PermissionVoter'])) {
            return $container->services['PHPMaker2026\\Project2\\PermissionVoter'];
        }

        return $container->services['PHPMaker2026\\Project2\\PermissionVoter'] = $instance;
    }
}
