<?php

namespace ContainerJZsQGll;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCheckerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\UserChecker' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\UserChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'UserCheckerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'UserChecker.php';

        return $container->services['PHPMaker2026\\Project2\\UserChecker'] = new \PHPMaker2026\Project2\UserChecker();
    }
}
