<?php

namespace ContainerJZsQGll;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProfileFactoryService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\UserProfileFactory' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\UserProfileFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'UserProfileFactory.php';

        return $container->services['PHPMaker2026\\Project2\\UserProfileFactory'] = new \PHPMaker2026\Project2\UserProfileFactory(($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)), ($container->services['PHPMaker2026\\Project2\\AppServiceLocator'] ?? self::getAppServiceLocatorService($container)), ($container->services['cache.app'] ?? self::getCache_AppService($container)));
    }
}
