<?php

namespace ContainerJZsQGll;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWarmupLanguageCacheCommand_CommandService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private 'PHPMaker2026\Project2\Command\WarmupLanguageCacheCommand.command' shared service.
     *
     * @return \Symfony\Component\Console\Command\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';

        $container->privates['PHPMaker2026\\Project2\\Command\\WarmupLanguageCacheCommand.command'] = $instance = new \Symfony\Component\Console\Command\Command();

        $instance->setCode(($container->services['PHPMaker2026\\Project2\\Command\\WarmupLanguageCacheCommand'] ?? $container->load('getWarmupLanguageCacheCommandService')));
        $instance->setName('app:cache:warmup-language');
        $instance->setAliases(['app:cache:warmup-language']);
        $instance->setDescription('Warms up the language cache');

        return $instance;
    }
}
