<?php

namespace ContainerXtzZZxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventManagerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'Doctrine\Common\EventManager' shared autowired service.
     *
     * @return \Doctrine\Common\EventManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Doctrine\\Common\\EventManager'] = new \Doctrine\Common\EventManager();
    }
}
