<?php

namespace ContainerXtzZZxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploadHandlerService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\FileUploadHandler' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\FileUploadHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'FileUploadHandler.php';

        return $container->services['PHPMaker2026\\Project2\\FileUploadHandler'] = new \PHPMaker2026\Project2\FileUploadHandler(($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)));
    }
}
