<?php

namespace ContainerXtzZZxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifier_FlashMessageImportanceMapperService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'notifier.flash_message_importance_mapper' shared autowired service.
     *
     * @return \Symfony\Component\Notifier\FlashMessage\BootstrapFlashMessageImportanceMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'notifier'.\DIRECTORY_SEPARATOR.'FlashMessage'.\DIRECTORY_SEPARATOR.'AbstractFlashMessageImportanceMapper.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'notifier'.\DIRECTORY_SEPARATOR.'FlashMessage'.\DIRECTORY_SEPARATOR.'FlashMessageImportanceMapperInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'notifier'.\DIRECTORY_SEPARATOR.'FlashMessage'.\DIRECTORY_SEPARATOR.'BootstrapFlashMessageImportanceMapper.php';

        return $container->services['notifier.flash_message_importance_mapper'] = new \Symfony\Component\Notifier\FlashMessage\BootstrapFlashMessageImportanceMapper();
    }
}
