<?php

namespace ContainerXtzZZxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPragmaRxTwoFactorAuthenticationService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the public 'PHPMaker2026\Project2\PragmaRxTwoFactorAuthentication' shared autowired service.
     *
     * @return \PHPMaker2026\Project2\PragmaRxTwoFactorAuthentication
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'TwoFactorAuthenticationInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'AbstractTwoFactorAuthentication.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PragmaRxTwoFactorAuthentication.php';

        $a = ($container->services['PHPMaker2026\\Project2\\UserProfile'] ?? self::getUserProfileService($container));

        if (isset($container->services['PHPMaker2026\\Project2\\PragmaRxTwoFactorAuthentication'])) {
            return $container->services['PHPMaker2026\\Project2\\PragmaRxTwoFactorAuthentication'];
        }
        $b = ($container->privates['notifier'] ?? $container->load('getNotifierService'));

        if (isset($container->services['PHPMaker2026\\Project2\\PragmaRxTwoFactorAuthentication'])) {
            return $container->services['PHPMaker2026\\Project2\\PragmaRxTwoFactorAuthentication'];
        }

        $instance = new \PHPMaker2026\Project2\PragmaRxTwoFactorAuthentication($a, ($container->services['PHPMaker2026\\Project2\\Language'] ?? self::getLanguageService($container)), $b);

        if (isset($container->services['PHPMaker2026\\Project2\\PragmaRxTwoFactorAuthentication'])) {
            return $container->services['PHPMaker2026\\Project2\\PragmaRxTwoFactorAuthentication'];
        }

        return $container->services['PHPMaker2026\\Project2\\PragmaRxTwoFactorAuthentication'] = $instance;
    }
}
