<?php

namespace ContainerXtzZZxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewAppointmentReportControllerlistService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EfXVwpA.PHPMaker2026\Project2\ViewAppointmentReportController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['services', 'PHPMaker2026\\Project2\\ViewAppointmentReportList', 'getViewAppointmentReportListService', true],
        ], [
            'page' => 'PHPMaker2026\\Project2\\ViewAppointmentReportList',
        ]))->withContext('PHPMaker2026\\Project2\\ViewAppointmentReportController::list()', $container);

        if (isset($container->privates['.service_locator.EfXVwpA.PHPMaker2026\\Project2\\ViewAppointmentReportController::list()'])) {
            return $container->privates['.service_locator.EfXVwpA.PHPMaker2026\\Project2\\ViewAppointmentReportController::list()'];
        }

        return $container->privates['.service_locator.EfXVwpA.PHPMaker2026\\Project2\\ViewAppointmentReportController::list()'] = $instance;
    }
}
