<?php

namespace ContainerXtzZZxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWarmupLanguageCacheCommand_Command_LazyService extends PHPMaker2026_Project2_KernelDevDebugContainer
{
    /**
     * Gets the private '.PHPMaker2026\Project2\Command\WarmupLanguageCacheCommand.command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.PHPMaker2026\\Project2\\Command\\WarmupLanguageCacheCommand.command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:cache:warmup-language', ['app:cache:warmup-language'], 'Warms up the language cache', false, #[\Closure(name: 'PHPMaker2026\\Project2\\Command\\WarmupLanguageCacheCommand.command', class: 'Symfony\\Component\\Console\\Command\\Command')] fn (): \Symfony\Component\Console\Command\Command => ($container->privates['PHPMaker2026\\Project2\\Command\\WarmupLanguageCacheCommand.command'] ?? $container->load('getWarmupLanguageCacheCommand_CommandService')));
    }
}
